### PR TITLE
Commented out requests package

### PR DESCRIPTION
**Pull request by souvikhaldar**
I was facing an error that requests module can't be imported, so commented out the requests module and now it's working just fine. Kindly approve this PR.

### CODE REVIEW

**Comment by souvikhaldar** [comment]
Let me know if I'm missing out on something.

**Comment by thehappydinoa** [comment]
@souvikhaldar Thank you for making this PR, have you tested to make sure all tools and functions still preform normally?

**Comment by souvikhaldar** [comment]
Yes everything seems to work fine now :)

**Comment by thehappydinoa** [comment]
@souvikhaldar Great, I did some testing myself. I will merge. Thank you for your contribution

**Comment by souvikhaldar** [comment]
More to come :) Thanks!

**Pull request merged**
