### PR TITLE
Update fsociety.py

### PR DESCRIPTION
**Pull request by thehappydinoa**
Fixed Style Issues

### CODE REVIEW

**Comment by Manisso** [comment]
Thanks for your help

**Comment by Manisso** [comment]
Thanks for your help

**Comment by thehappydinoa** [comment]
Hey would I be able to get some credit for my work? It looks like you just copied my edits

**Comment by Manisso** [comment]
Can I Have Your Fb To Talk To You In priv8 
or just add me On https://fb.me/dzmanisso

**Comment by UltimateHackers** [comment]
@thehappydinoa Thanks for strengthening my doubt xD
This guy is a jerk.

**Comment by thehappydinoa** [comment]
@UltimateHackers we actually had a great conversation and now I am a collaborator, if there is anything I can do to help you lmk

**Comment by UltimateHackers** [comment]
@thehappydinoa  Nothing much, he just ripped off one of my programs.

**Comment by thehappydinoa** [comment]
@UltimateHackers do you have a Twitter or something we can dm with?

**Comment by UltimateHackers** [comment]
@thehappydinoa [https://twitter.com/s0md3v](https://twitter.com/s0md3v)

**Comment by thehappydinoa** [comment]
@UltimateHackers just added you

**Comment by nitaibezerra** [comment]
If you guys dont wanna interact transparentely for collaboration, you should be concerned about privacy more seriously and avoid using Twitter. Go to Fediverse. Pick one instance in https://joinmastodon.org/ site.

However it would be much better to the project growth if everything is discussed openly. Or watch out forks comming...

**Comment by gabrielmacedoo** [comment]
File "fsociety.py", line 101
    """
      ^

**Comment by Manisso** [comment]
### @gabrielmacedoo  Don't Use Python3 Use Python :+1:  2 or just type 
`python fsociety`

**Comment by thehappydinoa** [comment]
@Manisso Hey should I spend some time working on making it python 3 compatible?

**Comment by Manisso** [comment]
IT WILL BE VERY USEFULL IF YOU DO IT   @thehappydinoa

**Comment by thehappydinoa** [comment]
@Manisso I have implemented Python 3 in a new branch

**Comment by Manisso** [comment]
Nice Job Thnx Bro

**Pull request closed without merging**
